#!/usr/bin/env Rscript
# =============================================================================
# 5_2_Circos_regulon_overlap.R
# Circos plot: regulon (target-gene) overlap among the 17 prioritized
# transcriptional drivers of ovarian cancer.
#
# Companion figure for Figure 3 (MRA NES vs signature score scatter,
# generated by 5_0_ovary_mra.R) in:
#   "Integrative transcriptomic and network-guided functional dependency
#    analysis reveals essential transcriptional drivers in ovarian cancer"
#
# Overview:
#   1. Load the final ARACNe-AP consolidated network (Regulator/Target/MI),
#      the same file consumed by 5_0_ovary_mra.R.
#   2. Load core_mra.tsv (output of 5_0_ovary_mra.R) to get NES/direction
#      for each of the 17 drivers.
#   3. Extract each driver's regulon (its ARACNe target-gene set).
#   4. Compute pairwise overlap (shared targets + Jaccard index) between
#      the 17 regulons.
#   5. Draw a Circos/chord diagram: sectors = the 17 drivers, grouped into
#      the functional modules described in the Discussion; an inner track
#      colors each sector by NES; ribbons connect driver pairs whose
#      regulons share target genes, width/alpha scaled by overlap size.
#   6. Save the figure as PDF (vector) and PNG (300 dpi), and print
#      diagnostic tables to the console for a sanity check.
#
# Input files (expected in this folder, 5_MRA/):
#   cancer_ovary_network_300bt_p1e-8.txt  — ARACNe-AP network (from aracneap.sh)
#   core_mra.tsv                          — MRA results table (from 5_0_ovary_mra.R)
#
# Output files (written to this folder, 5_MRA/):
#   5_2_1_circos_17drivers_regulon_overlap.pdf
#   5_2_1_circos_17drivers_regulon_overlap.png
#
# Run with the working directory set to 5_MRA/, e.g.:
#   setwd("~/Ovary_signatures/5_MRA"); source("5_2_Circos_regulon_overlap.R")
# or from a terminal: cd 5_MRA && Rscript 5_2_Circos_regulon_overlap.R
#
# Needs: circlize, dplyr, tidyr, readr (auto-installed if missing).
# NOT executed/tested in the environment that authored this script (no R
# available there) -- treat the first local run as a shakedown run and read
# the console warnings before trusting the output figure.
#
# KNOWN OPEN QUESTIONS (flag for Joel/Daniel before treating this as final)
#   - CHAF1B is grouped here under "Chromatin/centromere" because that is how
#     the Discussion describes it (CAF-1 histone chaperone). The Results
#     section instead lists CHAF1B among the "comparatively uncharacterized"
#     drivers together with KCMF1/GMNN/WDHD1/ELOC. Pick whichever framing you
#     want to keep and edit the `modules` list below accordingly -- it is a
#     one-line change.
#   - This script does NOT yet use DepMap/CRISPR dependency scores (Figure 4,
#     from 6_Depmap_ovary/) to color or size nodes by essentiality. If Joel
#     can share the per-gene median DepMap dependency table for the 17
#     drivers (and ideally the full 101 HD-gene set), we can add a third
#     track encoding that, tying Figures 3+4 together in one integrative
#     panel. Natural home for that table would be 6_Depmap_ovary/.
# =============================================================================

## ---- 0. Setup -------------------------------------------------------------

required_pkgs <- c("circlize", "dplyr", "tidyr", "readr")
missing_pkgs <- setdiff(required_pkgs, rownames(installed.packages()))
if (length(missing_pkgs) > 0) install.packages(missing_pkgs, repos = "https://cloud.r-project.org")

suppressPackageStartupMessages({
  library(circlize)
  library(dplyr)
  library(tidyr)
  library(readr)
})

## ---- 1. Paths & parameters -------------------------------------------------
# Relative paths assume the working directory is 5_MRA/ (same convention
# used by 5_0_ovary_mra.R and 5_1_Elbow_TF.R).

NETWORK_FILE   <- "cancer_ovary_network_300bt_p1e-8.txt"   # Regulator / Target / MI / pvalue
MRA_TABLE_FILE <- "core_mra.tsv"                           # TF / NES / direction / signature_score / ...
OUT_PREFIX     <- "5_2_1_circos_17drivers_regulon_overlap"

MIN_SHARED_TARGETS <- 3     # only draw a ribbon if regulons share >= this many targets
                             # (raise/lower to declutter or reveal more links)

## ---- 2. The 17 prioritized drivers, grouped into functional modules -------
# (as described in Results 5.3 / Discussion of the manuscript)

modules <- list(
  "G2/M & mitosis"           = c("PLK1", "CDK1", "AURKB", "CCNA2", "CDK2"),
  "DNA-damage checkpoint"    = c("CHEK1", "TIMELESS"),
  "Chromatin / centromere"   = c("ACTL6A", "CENPA", "CHAF1B"),
  "RNA processing"           = c("SRSF2"),
  "Survival / apoptosis"     = c("BIRC5", "HMGB3"),
  "Underexplored"            = c("KCMF1", "GMNN", "WDHD1", "ELOC")
)

driver_module <- stack(modules) |>
  rename(gene = values, module = ind) |>
  mutate(gene = as.character(gene), module = as.character(module))

drivers <- driver_module$gene
stopifnot(length(drivers) == 17, length(unique(drivers)) == 17)

module_colors <- c(
  "G2/M & mitosis"         = "#1B9E77",
  "DNA-damage checkpoint"  = "#D95F02",
  "Chromatin / centromere" = "#7570B3",
  "RNA processing"         = "#E7298A",
  "Survival / apoptosis"   = "#66A61E",
  "Underexplored"          = "#999999"
)

## ---- 3. Load MRA results (NES / direction) for the 17 drivers -------------

mra <- read_tsv(MRA_TABLE_FILE, show_col_types = FALSE)

mra_17 <- mra %>%
  filter(TF %in% drivers) %>%
  select(gene = TF, NES, direction, signature_score)

missing_from_mra <- setdiff(drivers, mra_17$gene)
if (length(missing_from_mra) > 0) {
  warning("These drivers were NOT found in ", MRA_TABLE_FILE, ": ",
          paste(missing_from_mra, collapse = ", "),
          " -- check gene symbols / file version with Joel before proceeding.")
}

driver_info <- driver_module %>%
  left_join(mra_17, by = "gene") %>%
  arrange(match(module, names(modules)), desc(NES))

cat("\n=== Driver table (module, NES, direction) ===\n")
print(driver_info, n = Inf)

## ---- 4. Load ARACNe network and extract regulons for the 17 drivers ------

cat("\nReading network file (this is the big ~40MB file, may take a bit)...\n")
net <- read_tsv(NETWORK_FILE, show_col_types = FALSE)

# sanity check on expected column names
stopifnot(all(c("Regulator", "Target") %in% names(net)))

regulons <- lapply(drivers, function(g) {
  unique(net$Target[net$Regulator == g])
})
names(regulons) <- drivers

regulon_sizes <- lengths(regulons)
cat("\n=== Regulon sizes (number of ARACNe targets) per driver ===\n")
print(sort(regulon_sizes, decreasing = TRUE))

zero_regulon <- names(regulon_sizes)[regulon_sizes == 0]
if (length(zero_regulon) > 0) {
  warning("These drivers have ZERO targets in the network file (not present as ",
          "'Regulator', or filtered out upstream): ", paste(zero_regulon, collapse = ", "),
          ". Confirm with Joel whether a different/updated network file should be used.")
}

## ---- 5. Pairwise regulon overlap (shared targets + Jaccard) ---------------

pairs <- combn(drivers, 2, simplify = FALSE)

overlap_df <- do.call(rbind, lapply(pairs, function(pr) {
  a <- regulons[[pr[1]]]; b <- regulons[[pr[2]]]
  shared <- length(intersect(a, b))
  union_n <- length(union(a, b))
  jaccard <- if (union_n > 0) shared / union_n else 0
  data.frame(from = pr[1], to = pr[2], shared = shared, jaccard = jaccard)
}))

overlap_df <- overlap_df %>% arrange(desc(shared))

cat("\n=== Top 15 driver pairs by shared regulon targets ===\n")
print(head(overlap_df, 15))

links <- overlap_df %>% filter(shared >= MIN_SHARED_TARGETS)

cat("\n", nrow(links), " links pass the MIN_SHARED_TARGETS = ", MIN_SHARED_TARGETS,
    " threshold (out of ", nrow(overlap_df), " possible pairs).\n", sep = "")

if (nrow(links) == 0) {
  warning("No pairs pass the overlap threshold -- lower MIN_SHARED_TARGETS, ",
          "or double check that the network file / gene symbols match.")
}

## ---- 6. Build the Circos plot ---------------------------------------------

sector_order <- driver_info$gene
sector_module <- setNames(driver_info$module, driver_info$gene)
sector_nes    <- setNames(driver_info$NES, driver_info$gene)

# color scale for NES within the activated range seen in this analysis
nes_col_fun <- colorRamp2(
  c(min(sector_nes, na.rm = TRUE), max(sector_nes, na.rm = TRUE)),
  c("#FEE0D2", "#A50F15")   # light -> dark red (all 17 are "Activated")
)

draw_circos <- function() {
  circos.clear()
  circos.par(gap.after = c(rep(2, length(sector_order) - 1), 8),
             start.degree = 90, track.margin = c(0.01, 0.01))

  circos.initialize(factors = sector_order, xlim = c(0, 1))

  # Track 1 (outer): functional module color band + gene label
  circos.trackPlotRegion(factors = sector_order, ylim = c(0, 1), track.height = 0.08,
    panel.fun = function(x, y) {
      sector <- get.cell.meta.data("sector.index")
      circos.rect(0, 0, 1, 1, col = module_colors[sector_module[sector]], border = NA)
      circos.text(0.5, 1.8, sector, facing = "clockwise", niceFacing = TRUE,
                   cex = 0.75, font = 2)
    })

  # Track 2: NES bar (activation strength)
  circos.trackPlotRegion(factors = sector_order, ylim = c(0, 1), track.height = 0.08,
    panel.fun = function(x, y) {
      sector <- get.cell.meta.data("sector.index")
      circos.rect(0, 0, 1, 1, col = nes_col_fun(sector_nes[sector]), border = "white")
    })

  # Links: ribbons for regulon overlap, colored by module of origin,
  # cross-module links drawn thinner/greyer to keep the plot readable
  for (i in seq_len(nrow(links))) {
    same_module <- sector_module[links$from[i]] == sector_module[links$to[i]]
    col <- if (same_module) {
      add_transparency(module_colors[sector_module[links$from[i]]], 0.55)
    } else {
      add_transparency("grey40", 0.85)
    }
    lwd <- 0.5 + 2 * (links$shared[i] / max(links$shared))
    circos.link(links$from[i], 0.5, links$to[i], 0.5, col = col, lwd = lwd)
  }

  legend("bottomleft", legend = names(module_colors), fill = module_colors,
         bty = "n", cex = 0.65, title = "Functional module")
  legend("bottomright", legend = c("weaker", "", "stronger"),
         title = "Regulon overlap", bty = "n", cex = 0.65,
         lty = 1, lwd = c(0.5, 1.5, 2.5), col = "grey40")
}

pdf(paste0(OUT_PREFIX, ".pdf"), width = 7, height = 7)
draw_circos()
dev.off()

png(paste0(OUT_PREFIX, ".png"), width = 7, height = 7, units = "in", res = 300)
draw_circos()
dev.off()

cat("\nSaved: ", OUT_PREFIX, ".pdf and .png\n", sep = "")
cat("Review the console tables above before dropping this into the manuscript ",
    "-- especially the 'zero_regulon' and 'missing_from_mra' warnings, if any.\n", sep = "")
