#!/usr/bin/env Rscript
# =============================================================================
# 5_2_Circos_regulon_overlap.R
# Circos plot: regulon (target-gene) overlap among the 17 prioritized
# transcriptional drivers of ovarian cancer.
#
# Companion figure for Figure 3 (MRA NES vs signature score scatter,
# generated by 5_0_ovary_mra.R) in:
#   "Integrative transcriptomic and network-guided functional dependency
#    analysis reveals essential transcriptional drivers in ovarian cancer"
#
# Overview:
#   1. Load the final ARACNe-AP consolidated network (Regulator/Target/MI),
#      the same file consumed by 5_0_ovary_mra.R.
#   2. Load core_mra.tsv (output of 5_0_ovary_mra.R) to get NES/direction
#      for each of the 17 drivers.
#   3. Extract each driver's regulon (its ARACNe target-gene set).
#   4. Compute pairwise overlap (shared targets + Jaccard index) between
#      the 17 regulons.
#   5. Draw a Circos/CHORD diagram via circlize::chordDiagram(): sectors =
#      the 17 drivers, grouped into the functional modules described in the
#      Discussion and colored by module (chordDiagram's own "grid" track) +
#      gene-symbol label. NES is still used to order drivers within a module
#      (via core_mra.tsv) but is no longer drawn as its own color ring -- an
#      earlier attempt at a second NES-colored band hit a circlize rendering
#      bug where an explicit per-cell ribbon `col` matrix combined with >= 2
#      preAllocateTracks entries causes the outer custom track to silently
#      overwrite the grid ring underneath it (reproduced and confirmed in
#      isolation; see the comment above `grid_col` below). Ribbons connect
#      driver pairs whose regulons overlap (Jaccard >= MIN_JACCARD). Unlike
#      the first version of this figure,
#      sector width is NOT fixed/equal: chordDiagram() sizes every driver's
#      arc proportionally to its DEGREE -- the number of other drivers it is
#      linked to after the Jaccard filter -- so a driver tightly coupled to
#      several others (e.g. the G2/M & mitosis hub) gets a visibly wide arc,
#      and a peripheral driver with one or two links gets a thin arc (drivers
#      with ZERO qualifying links get a small placeholder sector so they
#      still appear on the map). Ribbon color still distinguishes same-module
#      (module color) vs cross-module (grey) pairs as before; ribbon OPACITY
#      now carries the actual Jaccard magnitude (darker/more saturated =
#      stronger overlap), since ribbon body width is spoken for by the degree
#      encoding. This mirrors the width(count)/opacity(magnitude) split used
#      in the companion figure 5_3_Circos_driver_hallmark.R.
#   6. Save the figure as PDF (vector) and PNG (300 dpi), and print
#      diagnostic tables to the console for a sanity check.
#
# Input files (expected in this folder, 5_MRA/):
#   cancer_ovary_network_300bt_p1e-8.txt  — ARACNe-AP network (from aracneap.sh)
#   core_mra.tsv                          — MRA results table (from 5_0_ovary_mra.R)
#
# Output files (written to this folder, 5_MRA/):
#   5_2_1_circos_17drivers_regulon_overlap.pdf
#   5_2_1_circos_17drivers_regulon_overlap.png
#
# Run with the working directory set to 5_MRA/, e.g.:
#   setwd("~/Ovary_signatures/5_MRA"); source("5_2_Circos_regulon_overlap.R")
# or from a terminal: cd 5_MRA && Rscript 5_2_Circos_regulon_overlap.R
#
# Needs: circlize, dplyr, tidyr, readr (auto-installed if missing).
# NOT executed/tested in the environment that authored this script (no R
# available there) -- treat the first local run as a shakedown run and read
# the console warnings before trusting the output figure.
#
# KNOWN OPEN QUESTIONS (flag for Joel/Daniel before treating this as final)
#   - RESOLVED 2026-07-25: CHAF1B was tentatively grouped under
#     "Chromatin/centromere" (CAF-1 histone chaperone framing, per the
#     Discussion) in earlier drafts. Confirmed instead to belong with the
#     "comparatively uncharacterized" drivers, alongside KCMF1/GMNN/WDHD1/ELOC
#     (the Results-section framing) -- kept IDENTICAL to
#     5_3_Circos_driver_hallmark.R on purpose, so both figures tell a
#     consistent module story; if this ever needs to change again, change it
#     in both files.
#   - This script does NOT yet use DepMap/CRISPR dependency scores (Figure 4,
#     from 6_Depmap_ovary/) to color or size nodes by essentiality. If Joel
#     can share the per-gene median DepMap dependency table for the 17
#     drivers (and ideally the full 101 HD-gene set), we can add a third
#     track encoding that, tying Figures 3+4 together in one integrative
#     panel. Natural home for that table would be 6_Depmap_ovary/.
# =============================================================================

## ---- 0. Setup -------------------------------------------------------------

required_pkgs <- c("circlize", "dplyr", "tidyr", "readr", "png")
missing_pkgs <- setdiff(required_pkgs, rownames(installed.packages()))
if (length(missing_pkgs) > 0) install.packages(missing_pkgs, repos = "https://cloud.r-project.org")

suppressPackageStartupMessages({
  library(circlize)
  library(dplyr)
  library(tidyr)
  library(readr)
})

## ---- 1. Paths & parameters -------------------------------------------------
# Relative paths assume the working directory is 5_MRA/ (same convention
# used by 5_0_ovary_mra.R and 5_1_Elbow_TF.R).

NETWORK_FILE   <- "cancer_ovary_network_300bt_p1e-8.txt"   # Regulator / Target / MI / pvalue
MRA_TABLE_FILE <- "core_mra.tsv"                           # TF / NES / direction / signature_score / ...
OUT_PREFIX     <- "5_2_1_circos_17drivers_regulon_overlap"

MIN_SHARED_TARGETS <- 3     # secondary floor: never draw a ribbon below this many shared
                             # targets, regardless of Jaccard (guards against tiny regulons
                             # producing a spuriously high Jaccard from just 1-2 shared genes)
MIN_JACCARD <- 0.15         # PRIMARY filter: only draw a ribbon if the Jaccard index of the
                             # two regulons is >= this. Regulon sizes span ~20x among these 17
                             # drivers (125 targets for BIRC5 vs 2579 for KCMF1), so filtering
                             # on raw shared-target counts lets the largest regulons (KCMF1,
                             # SRSF2, ELOC, ACTL6A) dominate the plot with links that are large
                             # in absolute terms but tiny relative to regulon size (e.g.
                             # SRSF2-KCMF1: 508 shared targets but Jaccard = 0.13). Jaccard
                             # normalizes for regulon size and highlights genuinely coordinated
                             # pairs -- with this cutoff the top links are almost all within the
                             # G2/M & mitosis module (PLK1-CCNA2, CDK1-CCNA2, PLK1-CDK1, ...),
                             # which matches the manuscript's Discussion narrative much better
                             # than the previous count-based threshold (which passed 134/136
                             # possible pairs -- essentially everything).
                             # (raise/lower to declutter or reveal more links; try 0.20 for an
                             # even sparser plot, ~19 links)

## ---- 2. The 17 prioritized drivers, grouped into functional modules -------
# (as described in Results 5.3 / Discussion of the manuscript)

modules <- list(
  "G2/M & mitosis"           = c("PLK1", "CDK1", "AURKB", "CCNA2", "CDK2"),
  "DNA-damage checkpoint"    = c("CHEK1", "TIMELESS"),
  "Chromatin / centromere"   = c("ACTL6A", "CENPA"),
  "RNA processing"           = c("SRSF2"),
  "Survival / apoptosis"     = c("BIRC5", "HMGB3"),
  "Underexplored"            = c("KCMF1", "GMNN", "WDHD1", "ELOC", "CHAF1B")
)

driver_module <- as_tibble(stack(modules)) |>
  rename(gene = values, module = ind) |>
  mutate(gene = as.character(gene), module = as.character(module))

drivers <- driver_module$gene
stopifnot(length(drivers) == 17, length(unique(drivers)) == 17)

module_colors <- c(
  "G2/M & mitosis"         = "#1B9E77",
  "DNA-damage checkpoint"  = "#D95F02",
  "Chromatin / centromere" = "#7570B3",
  "RNA processing"         = "#E7298A",
  "Survival / apoptosis"   = "#66A61E",
  "Underexplored"          = "#999999"
)

## ---- 3. Load MRA results (NES / direction) for the 17 drivers -------------

mra <- read_tsv(MRA_TABLE_FILE, show_col_types = FALSE)

mra_17 <- mra %>%
  filter(TF %in% drivers) %>%
  select(gene = TF, NES, direction, signature_score)

missing_from_mra <- setdiff(drivers, mra_17$gene)
if (length(missing_from_mra) > 0) {
  warning("These drivers were NOT found in ", MRA_TABLE_FILE, ": ",
          paste(missing_from_mra, collapse = ", "),
          " -- check gene symbols / file version with Joel before proceeding.")
}

driver_info <- driver_module %>%
  left_join(mra_17, by = "gene") %>%
  arrange(match(module, names(modules)), desc(NES))

cat("\n=== Driver table (module, NES, direction) ===\n")
print(driver_info, n = Inf)

## ---- 4. Load ARACNe network and extract regulons for the 17 drivers ------

cat("\nReading network file (this is the big ~40MB file, may take a bit)...\n")
net <- read_tsv(NETWORK_FILE, show_col_types = FALSE)

# sanity check on expected column names
stopifnot(all(c("Regulator", "Target") %in% names(net)))

regulons <- lapply(drivers, function(g) {
  unique(net$Target[net$Regulator == g])
})
names(regulons) <- drivers

regulon_sizes <- lengths(regulons)
cat("\n=== Regulon sizes (number of ARACNe targets) per driver ===\n")
print(sort(regulon_sizes, decreasing = TRUE))

zero_regulon <- names(regulon_sizes)[regulon_sizes == 0]
if (length(zero_regulon) > 0) {
  warning("These drivers have ZERO targets in the network file (not present as ",
          "'Regulator', or filtered out upstream): ", paste(zero_regulon, collapse = ", "),
          ". Confirm with Joel whether a different/updated network file should be used.")
}

## ---- 5. Pairwise regulon overlap (shared targets + Jaccard) ---------------

pairs <- combn(drivers, 2, simplify = FALSE)

overlap_df <- do.call(rbind, lapply(pairs, function(pr) {
  a <- regulons[[pr[1]]]; b <- regulons[[pr[2]]]
  shared <- length(intersect(a, b))
  union_n <- length(union(a, b))
  jaccard <- if (union_n > 0) shared / union_n else 0
  data.frame(from = pr[1], to = pr[2], shared = shared, jaccard = jaccard)
}))

overlap_df <- overlap_df %>% arrange(desc(shared))

cat("\n=== Top 15 driver pairs by shared regulon targets ===\n")
print(head(overlap_df, 15))

links <- overlap_df %>% filter(jaccard >= MIN_JACCARD, shared >= MIN_SHARED_TARGETS)

cat("\n", nrow(links), " links pass the MIN_JACCARD = ", MIN_JACCARD,
    " (and MIN_SHARED_TARGETS = ", MIN_SHARED_TARGETS, ") threshold(s) (out of ",
    nrow(overlap_df), " possible pairs).\n", sep = "")

if (nrow(links) == 0) {
  warning("No pairs pass the overlap threshold -- lower MIN_JACCARD / MIN_SHARED_TARGETS, ",
          "or double check that the network file / gene symbols match.")
}

## ---- 6. Build the CHORD diagram (sector width = degree) -------------------

sector_order <- driver_info$gene
sector_module <- setNames(driver_info$module, driver_info$gene)
n_sectors     <- length(sector_order)

# Square adjacency matrix, same 17 names on rows and columns -- chordDiagram()
# merges same-named rows/cols into a single sector per driver, with sector
# size = sum of that driver's row+column values. Only the upper triangle is
# filled (each unordered pair appears once in `links`), value = 1 per edge so
# sector width is a pure DEGREE count, not weighted by Jaccard magnitude.
value_mat <- matrix(0, nrow = n_sectors, ncol = n_sectors,
                     dimnames = list(sector_order, sector_order))
for (i in seq_len(nrow(links))) {
  value_mat[links$from[i], links$to[i]] <- 1
}

degree <- rowSums(value_mat) + colSums(value_mat)
cat("\n=== Driver degree (number of Jaccard-qualifying partners) ===\n")
print(sort(degree, decreasing = TRUE))

# chordDiagram() silently DROPS any sector whose total row+col value is 0 --
# a driver with no Jaccard-qualifying partner at this threshold would simply
# vanish from the figure instead of appearing as a (thin) unconnected sector.
# Give each zero-degree driver a tiny self-value on the matrix diagonal to
# keep its sector alive at a minimal width; keep.diagonal = FALSE (below,
# where chordDiagram() is called) means this self-value never draws a
# visible self-loop ribbon -- it only keeps the sector on the map.
zero_degree_drivers <- names(degree)[degree == 0]
if (length(zero_degree_drivers) > 0) {
  cat("\nNOTE: these drivers have ZERO Jaccard-qualifying partners at MIN_JACCARD = ",
      MIN_JACCARD, " and will be drawn as a minimal placeholder sector (no ribbons): ",
      paste(zero_degree_drivers, collapse = ", "), "\n", sep = "")
  for (g in zero_degree_drivers) value_mat[g, g] <- 0.3
}

# Per-cell ribbon color: same-module pairs get their module color, cross-
# module pairs get grey (as before); opacity within each group scales with
# Jaccard strength (darker/more saturated = stronger overlap) since ribbon
# body width is now spoken for by the degree encoding above.
max_jaccard <- max(links$jaccard)
col_mat <- matrix("#00000000", nrow = n_sectors, ncol = n_sectors,
                   dimnames = dimnames(value_mat))
for (i in seq_len(nrow(links))) {
  strength <- links$jaccard[i] / max_jaccard
  same_module <- sector_module[links$from[i]] == sector_module[links$to[i]]
  col_mat[links$from[i], links$to[i]] <- if (same_module) {
    add_transparency(module_colors[sector_module[links$from[i]]], 0.75 - 0.40 * strength)
  } else {
    add_transparency("grey40", 0.90 - 0.15 * strength)
  }
}

# chordDiagram()'s own "grid" annotation track carries the module color
# directly (the sector's "identity" color, matching the legend). An earlier
# version of this script tried to free up the grid ring for NES and draw
# module color as a second custom band instead, but that combination --
# an explicit per-cell `col` matrix together with >= 2 preAllocateTracks
# entries -- triggers what looks like a circlize rendering bug: the second
# custom track's fill silently overwrites/swallows the grid ring underneath
# it (verified in isolation: identical code with either the `col` matrix
# removed, or down to a single preAllocateTracks entry, renders correctly).
# Simplest robust fix -- and the same pattern already used successfully in
# 5_3_Circos_driver_hallmark.R -- is a single preAllocateTracks entry (the
# label) and no separate NES ring.
grid_col <- module_colors[sector_module[sector_order]]
names(grid_col) <- sector_order

draw_circos <- function() {
  # Allow gene-label text to spill past the device's default plotting region
  # instead of being clipped at the canvas edge (same fix as before). Canvas
  # widened beyond the default c(-1,1) for the same reason.
  old_par <- par(xpd = NA, mar = c(1, 1, 1, 1))
  on.exit(par(old_par), add = TRUE)

  circos.clear()
  circos.par(start.degree = 90, canvas.xlim = c(-1.3, 1.3), canvas.ylim = c(-1.3, 1.3))

  chordDiagram(
    value_mat,
    grid.col          = grid_col,
    col               = col_mat,
    order             = sector_order,
    directional       = 0,
    small.gap         = 2,
    annotationTrack   = "grid",     # module-colored band, see grid_col above
    annotationTrackHeight = 0.09,
    keep.diagonal     = FALSE,      # don't draw the placeholder self-loops
                                    # added above for zero-degree drivers
    preAllocateTracks = list(track.height = 0.10),   # reserved for the label
                                                      # track below (single
                                                      # entry -- see the note
                                                      # on grid_col above for
                                                      # why not two)
    link.sort         = TRUE,
    link.largest.ontop = TRUE
  )

  # Gene-symbol label (outermost, i.e. track.index = 2)
  circos.trackPlotRegion(track.index = 2, bg.border = NA, panel.fun = function(x, y) {
    sector <- get.cell.meta.data("sector.index")
    xcenter <- get.cell.meta.data("xcenter")
    circos.text(xcenter, 0.5, sector, facing = "clockwise", niceFacing = TRUE,
                 cex = 0.75, font = 2)
  })

  # Explicit (x, y) instead of "bottomleft"/"bottomright": those keywords
  # anchor to the padded canvas corner (canvas.ylim[1] = -1.3), well below
  # where the circle's own labels actually end (~ -0.8), leaving a dead gap
  # (same fix as in 5_3_Circos_driver_hallmark.R; see crop_png_whitespace()
  # below for the outer-margin side of the same problem).
  legend(x = -1.25, y = -0.85, legend = names(module_colors), fill = module_colors,
         bty = "n", cex = 0.65, ncol = 2, title = "Functional module")
  legend(x = 0.55, y = -0.85,
         legend = c("weaker", "", "stronger"),
         fill   = add_transparency("#1B9E77", c(0.75, 0.55, 0.35)),
         title  = "Regulon overlap\n(ribbon opacity ~ Jaccard)",
         bty = "n", cex = 0.6)
}

# Auto-crop the rendered PNG down to its actual content bounding box (plus a
# small pad) -- the programmatic version of a manual Photoshop crop. Reads
# the PNG back in, finds rows/cols that aren't (near-)white, and rewrites
# the file cropped to that box. Same helper as in 5_3_Circos_driver_hallmark.R.
crop_png_whitespace <- function(path, pad_px = 15, bg_threshold = 0.98) {
  img <- png::readPNG(path)
  rgb <- img[, , 1:3, drop = FALSE]
  is_bg <- (rgb[, , 1] > bg_threshold) & (rgb[, , 2] > bg_threshold) & (rgb[, , 3] > bg_threshold)
  is_content <- !is_bg
  rows <- which(apply(is_content, 1, any))
  cols <- which(apply(is_content, 2, any))
  if (length(rows) == 0 || length(cols) == 0) {
    warning("crop_png_whitespace(): no non-background content detected in ", path,
            " -- leaving the file unmodified.")
    return(invisible(NULL))
  }
  r0 <- max(1, min(rows) - pad_px);          r1 <- min(dim(img)[1], max(rows) + pad_px)
  c0 <- max(1, min(cols) - pad_px);          c1 <- min(dim(img)[2], max(cols) + pad_px)
  png::writePNG(img[r0:r1, c0:c1, , drop = FALSE], path)
  cat("Cropped ", path, ": ", dim(img)[2], "x", dim(img)[1], " -> ",
      c1 - c0 + 1, "x", r1 - r0 + 1, " px\n", sep = "")
}

pdf(paste0(OUT_PREFIX, ".pdf"), width = 7, height = 7)
draw_circos()
dev.off()

png(paste0(OUT_PREFIX, ".png"), width = 7, height = 7, units = "in", res = 300)
draw_circos()
dev.off()

crop_png_whitespace(paste0(OUT_PREFIX, ".png"))
# NB: the PDF is left uncropped -- it's a vector file, so trimming its page
# box is a trivial, lossless operation in Illustrator/Acrobat/Inkscape if
# needed, and doing it here would require an external tool (e.g. pdfcrop)
# this repo doesn't otherwise depend on.

cat("\nSaved: ", OUT_PREFIX, ".pdf and .png\n", sep = "")
cat("Review the console tables above before dropping this into the manuscript ",
    "-- especially the 'zero_regulon' and 'missing_from_mra' warnings, if any.\n", sep = "")
