#!/usr/bin/env Rscript
# =============================================================================
# 5_3_Circos_driver_hallmark.R
# Bipartite Circos plot: driver -> Hallmark (MSigDB) functional program, for
# the 17 prioritized transcriptional drivers of ovarian cancer.
#
# Companion / complementary figure to 5_2_Circos_regulon_overlap.R. That
# script draws driver <-> driver regulon-overlap ribbons and, after switching
# to a Jaccard-based threshold, is dominated by a single readable cluster
# (G2/M & mitosis) while most surviving cross-module links are thin grey
# lines -- informative about pairwise coordination, but it doesn't show what
# each regulon actually *does*. This script instead asks, per driver: "which
# Hallmark gene sets are over-represented among this driver's ARACNe target
# genes?" and draws driver -> Hallmark-term ribbons, i.e. a bipartite graph
# instead of a driver-driver graph.
#
# Companion figure for Figure 3 (MRA NES vs signature score scatter,
# generated by 5_0_ovary_mra.R) in:
#   "Integrative transcriptomic and network-guided functional dependency
#    analysis reveals essential transcriptional drivers in ovarian cancer"
#
# Overview:
#   1. Load the final ARACNe-AP consolidated network (Regulator/Target/MI),
#      the same file consumed by 5_0_ovary_mra.R and 5_2_Circos_regulon_overlap.R.
#   2. Extract each of the 17 drivers' regulon (ARACNe target-gene set) --
#      identical logic to 5_2_Circos_regulon_overlap.R.
#   3. Load the 50 Hallmark gene sets from MSigDB via msigdbr.
#   4. Run clusterProfiler::enricher() per driver (regulon genes vs Hallmark
#      gene sets), against a background/universe of all genes present in the
#      ARACNe network (see "On the ORA universe" below).
#   5. Filter to significant driver-term pairs (padj < PADJ_CUTOFF), then cap
#      to the top N terms per driver (TOP_N_PER_DRIVER) and optionally
#      require a term to recur across >= MIN_DRIVERS_PER_TERM drivers, to
#      keep the plot readable.
#   6. Draw a bipartite Circos/CHORD diagram via circlize::chordDiagram():
#      driver sectors (colored by the same functional module + palette as
#      5_2_Circos_regulon_overlap.R) on one half of the circle, Hallmark-term
#      sectors (neutral grey, to read visually as a different node type) on
#      the other half. Ribbons run driver -> term, colored by the origin
#      driver's module. Unlike 5_2 (and unlike this script's own first draft),
#      sector width is NOT fixed/equal: chordDiagram() sizes every sector
#      proportionally to the sum of its adjacent ribbon values, so a driver
#      whose regulon is strongly enriched across several Hallmark terms gets
#      a visibly wide arc, and a Hallmark term recurrently hit by many
#      drivers also gets a wide arc -- the arc width itself communicates
#      "how much this node participates," which fixed-width sectors could not
#      show. Ribbon (and therefore sector) width is driven by GeneRatio*100
#      (the % of the driver's regulon -- intersected with the universe --
#      that falls in that Hallmark term); ribbon opacity is a secondary
#      encoding of -log10(padj) (more significant = more opaque). This
#      combination was chosen over 5_2's raw-count trap on purpose: GeneRatio
#      is a proportion of each driver's own regulon size, so it does not
#      mechanically favor the two biggest regulons (KCMF1, SRSF2) the way a
#      raw shared-gene count would.
#   7. Save the figure as PDF (vector) and PNG (300 dpi), and print
#      diagnostic tables to the console for a sanity check.
#
# On the ORA universe/background:
#   4_ORA_clusterProfiler/4_ORA_core_bar.R does NOT use clusterProfiler's
#   default (the whole org.Hs.eg.db-annotated genome) -- it defines an
#   explicit, dataset-specific universe (there: the union of genes tested by
#   DESeq2/RRA across the 3 DE sources). The analogous, dataset-specific
#   choice here is "every gene ARACNe-AP had a chance to test as a
#   Regulator or Target when it built this network from ov_tcga_vst.tsv"
#   (that VST matrix itself is not present in this folder, but the network
#   file is its direct downstream product and is available). In practice:
#     ARACNE_UNIVERSE <- unique(c(net$Regulator, net$Target))   (~22.6k genes)
#   This is far closer to "genes expressed/tested in this TCGA-OV cohort"
#   than clusterProfiler::enricher()'s whole-genome default, and keeps the
#   background consistent with what a regulon target could possibly be.
#
# Input files (expected in this folder, 5_MRA/):
#   cancer_ovary_network_300bt_p1e-8.txt  — ARACNe-AP network (from aracneap.sh)
#
# Output files (written to this folder, 5_MRA/):
#   5_3_1_circos_17drivers_hallmark.pdf
#   5_3_1_circos_17drivers_hallmark.png
#
# Run with the working directory set to 5_MRA/, e.g.:
#   setwd("~/Ovary_signatures/5_MRA"); source("5_3_Circos_driver_hallmark.R")
# or from a terminal: cd 5_MRA && Rscript 5_3_Circos_driver_hallmark.R
#
# Needs: circlize, dplyr, tidyr, readr, clusterProfiler, msigdbr
# (auto-installed if missing).
#
# RESOLVED OPEN QUESTION (was: carried over from 5_2_Circos_regulon_overlap.R)
#   - CHAF1B was tentatively grouped under "Chromatin/centromere" (CAF-1
#     histone chaperone framing, per the Discussion) in earlier drafts of
#     this figure. Confirmed 2026-07-25: CHAF1B belongs with the
#     "comparatively uncharacterized" drivers instead, alongside
#     KCMF1/GMNN/WDHD1/ELOC (the Results-section framing). Kept IDENTICAL to
#     5_2_Circos_regulon_overlap.R on purpose, so both figures tell a
#     consistent module story -- if this ever needs to change again, change
#     it in both files.
# =============================================================================

## ---- 0. Setup -------------------------------------------------------------

required_pkgs <- c("circlize", "dplyr", "tidyr", "readr", "clusterProfiler", "msigdbr", "png")
missing_pkgs <- setdiff(required_pkgs, rownames(installed.packages()))
if (length(missing_pkgs) > 0) install.packages(missing_pkgs, repos = "https://cloud.r-project.org")

suppressPackageStartupMessages({
  library(circlize)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(clusterProfiler)
  library(msigdbr)
})

## ---- 1. Paths & parameters -------------------------------------------------

NETWORK_FILE <- "cancer_ovary_network_300bt_p1e-8.txt"   # Regulator / Target / MI / pvalue
OUT_PREFIX   <- "5_3_1_circos_17drivers_hallmark"

PADJ_CUTOFF <- 0.05    # BH-adjusted p-value cutoff for a driver-term pair to
                        # count as "significant" at all (matches the P_ORA /
                        # padj convention used elsewhere in this repo).

TOP_N_PER_DRIVER <- 12 # PRIMARY declutter knob: keep at most this many
                        # Hallmark terms per driver (ranked by padj), among
                        # those passing PADJ_CUTOFF. No driver has more than
                        # 12 significant terms (KCMF1's 12 is the max across
                        # all 17; verified interactively), so 12 = "keep every
                        # significant term for every driver" -- i.e. this cap
                        # is effectively OFF and MIN_DRIVERS_PER_TERM below is
                        # the only active declutter knob. At this setting all
                        # 99 significant driver-term pairs / 16 unique terms
                        # are drawn, which turned out to still be readable.
                        # Lower to 5 (the original, more conservative default)
                        # for a sparser plot (~76 links / 11 unique terms), or
                        # to 3 for sparser still (~50 links / 8 terms).

MIN_DRIVERS_PER_TERM <- 1   # SECONDARY declutter knob (applied after the
                        # TOP_N_PER_DRIVER cap): drop a Hallmark term
                        # entirely if it recurs in fewer than this many
                        # drivers. Default 1 = inactive (keep every term that
                        # survives the per-driver cap, including singletons
                        # like a driver's own idiosyncratic top hit). Raise
                        # to 2 to prune singleton terms (removes ~2 terms /
                        # 2 links in this dataset) and keep only recurring,
                        # cross-driver programs -- use this if the term side
                        # of the circle looks cluttered with one-off sectors.

## ---- 2. The 17 prioritized drivers, grouped into functional modules -------
# (as described in Results 5.3 / Discussion of the manuscript; IDENTICAL to
# 5_2_Circos_regulon_overlap.R -- see the resolved open question in the
# header above)

modules <- list(
  "G2/M & mitosis"           = c("PLK1", "CDK1", "AURKB", "CCNA2", "CDK2"),
  "DNA-damage checkpoint"    = c("CHEK1", "TIMELESS"),
  "Chromatin / centromere"   = c("ACTL6A", "CENPA"),
  "RNA processing"           = c("SRSF2"),
  "Survival / apoptosis"     = c("BIRC5", "HMGB3"),
  "Underexplored"            = c("KCMF1", "GMNN", "WDHD1", "ELOC", "CHAF1B")
)

driver_module <- as_tibble(stack(modules)) |>
  rename(gene = values, module = ind) |>
  mutate(gene = as.character(gene), module = as.character(module))

drivers <- driver_module$gene
stopifnot(length(drivers) == 17, length(unique(drivers)) == 17)

module_colors <- c(
  "G2/M & mitosis"         = "#1B9E77",
  "DNA-damage checkpoint"  = "#D95F02",
  "Chromatin / centromere" = "#7570B3",
  "RNA processing"         = "#E7298A",
  "Survival / apoptosis"   = "#66A61E",
  "Underexplored"          = "#999999"
)

TERM_SECTOR_COLOR <- "#F0F0F0"   # neutral fill for Hallmark-term sectors --
                                 # deliberately distinct from every module
                                 # color (incl. "Underexplored" grey #999999)
                                 # so the two node types (driver vs term) are
                                 # visually unambiguous at a glance.

## ---- 3. Load ARACNe network, extract regulons, define the ORA universe ---

cat("Reading network file (this is the big ~40MB file, may take a bit)...\n")
net <- read_tsv(NETWORK_FILE, show_col_types = FALSE)
stopifnot(all(c("Regulator", "Target") %in% names(net)))

regulons <- lapply(drivers, function(g) unique(net$Target[net$Regulator == g]))
names(regulons) <- drivers

regulon_sizes <- lengths(regulons)
cat("\n=== Regulon sizes (number of ARACNe targets) per driver ===\n")
print(sort(regulon_sizes, decreasing = TRUE))

zero_regulon <- names(regulon_sizes)[regulon_sizes == 0]
if (length(zero_regulon) > 0) {
  warning("These drivers have ZERO targets in the network file (not present as ",
          "'Regulator', or filtered out upstream): ", paste(zero_regulon, collapse = ", "),
          ". Confirm with Joel whether a different/updated network file should be used.")
}

ARACNE_UNIVERSE <- unique(c(net$Regulator, net$Target))
cat("\n=== ORA universe/background ===\n")
cat("Genes in ARACNe network (Regulator U Target), used as ORA universe: ",
    length(ARACNE_UNIVERSE), "\n", sep = "")

# Defensive check: every regulon gene should already be a subset of the
# universe by construction (targets come straight from `net`) -- if this
# ever fires, something is inconsistent between how `net` was read and how
# the universe was built above.
targets_outside_universe <- unlist(lapply(names(regulons), function(g) {
  bad <- setdiff(regulons[[g]], ARACNE_UNIVERSE)
  if (length(bad) > 0) {
    warning(g, ": ", length(bad), " regulon target(s) are NOT in ARACNE_UNIVERSE ",
            "-- this should be impossible if the universe was built from the same ",
            "`net` object; double check for duplicate reads / stale objects.")
  }
  bad
}))
if (length(targets_outside_universe) == 0) {
  cat("OK: every driver's regulon is fully contained in ARACNE_UNIVERSE (as expected).\n")
}

## ---- 4. Hallmark gene sets (MSigDB, via msigdbr) --------------------------

# msigdbr >= 10.0 deprecated the category/subcategory arguments in favor of
# collection/subcollection (species = "Homo sapiens", category = "H" from the
# task spec still works but prints a deprecation warning); using the current
# non-deprecated call for a clean console.
hallmark <- msigdbr(species = "human", collection = "H")

term2gene <- hallmark %>% select(gs_name, gene_symbol) %>% distinct()
term2name <- hallmark %>%
  distinct(gs_name) %>%
  mutate(term_label = gsub("_", " ", sub("^HALLMARK_", "", gs_name)))

cat("\nLoaded ", length(unique(term2gene$gs_name)), " Hallmark gene sets (",
    nrow(term2gene), " gene-set/gene rows).\n", sep = "")

## ---- 5. Per-driver over-representation analysis (ORA) ---------------------

run_ora_one_driver <- function(driver, genes) {
  if (length(genes) == 0) return(data.frame())
  eg <- tryCatch({
    enricher(
      gene          = genes,
      universe      = ARACNE_UNIVERSE,
      TERM2GENE     = term2gene,
      TERM2NAME     = term2name %>% select(gs_name, term_label),
      pAdjustMethod = "BH",
      pvalueCutoff  = 1,   # keep everything here; we filter on padj below
      qvalueCutoff  = 1,
      minGSSize     = 5,
      maxGSSize     = 2000
    )
  }, error = function(e) {
    warning("enricher() failed for driver ", driver, ": ", conditionMessage(e))
    NULL
  })
  if (is.null(eg)) return(data.frame())
  df <- as.data.frame(eg)
  if (nrow(df) == 0) return(df)
  df$driver <- driver
  df
}

ora_all <- as_tibble(bind_rows(lapply(drivers, function(g) run_ora_one_driver(g, regulons[[g]]))))
# NOTE: bind_rows() of a list of as.data.frame(enricher_result) objects can
# come back as a plain data.frame rather than a tibble (observed with this
# dplyr build) -- as_tibble() here guarantees tibble semantics downstream,
# avoiding the same print(n=Inf)/na.print partial-matching trap fixed in
# 5_2_Circos_regulon_overlap.R (stack() there, bind_rows() here).

# Sanity check: GeneRatio's numerator should never exceed its denominator,
# and Count should match GeneRatio's numerator -- if either fails, something
# is wrong with how enricher() parsed the input (flag it rather than silently
# plotting garbage).
parse_ratio_num_den <- function(x) {
  parts <- strsplit(x, "/", fixed = TRUE)
  data.frame(num = as.numeric(vapply(parts, `[`, character(1), 1)),
             den = as.numeric(vapply(parts, `[`, character(1), 2)))
}
if (nrow(ora_all) > 0) {
  gr <- parse_ratio_num_den(ora_all$GeneRatio)
  ora_all$GeneRatio_num <- gr$num / gr$den   # e.g. 0.12 for "6/50" -- carried
                                              # through sig_all/links below and
                                              # used as the chord/ribbon width
  inconsistent <- which(gr$num > gr$den | gr$num != ora_all$Count)
  if (length(inconsistent) > 0) {
    warning(length(inconsistent), " row(s) have an inconsistent GeneRatio/Count -- ",
            "check the enricher() output for: ",
            paste(unique(ora_all$driver[inconsistent]), collapse = ", "))
  }
  padj_na_but_p_not <- which(is.na(ora_all$p.adjust) & !is.na(ora_all$pvalue))
  if (length(padj_na_but_p_not) > 0) {
    warning(length(padj_na_but_p_not), " row(s) have NA padj despite a non-NA raw ",
            "p-value -- check pAdjustMethod behavior / ties.")
  }
}

cat("\n=== Hallmark terms tested per driver (any p-value; before filtering) ===\n")
print(ora_all %>% count(driver, name = "n_terms_tested") %>% arrange(desc(n_terms_tested)))

sig_all <- ora_all %>% filter(!is.na(p.adjust), p.adjust < PADJ_CUTOFF)

cat("\n=== Significant Hallmark terms per driver (padj < ", PADJ_CUTOFF,
    "), before TOP_N_PER_DRIVER cap ===\n", sep = "")
sig_counts <- sig_all %>% count(driver, name = "n_sig_terms") %>% arrange(desc(n_sig_terms))
print(sig_counts)

zero_sig_drivers <- setdiff(drivers, unique(sig_all$driver))
if (length(zero_sig_drivers) > 0) {
  warning("These drivers have ZERO significant Hallmark terms at padj < ", PADJ_CUTOFF,
          ": ", paste(zero_sig_drivers, collapse = ", "),
          " -- they will be drawn as a bare sector with no ribbons. Consider raising ",
          "PADJ_CUTOFF or checking the regulon for these drivers.")
}

cat("\nTotal significant driver-term pairs (padj < ", PADJ_CUTOFF, "): ",
    nrow(sig_all), " out of ", nrow(ora_all), " tested.\n", sep = "")

## ---- 6. Declutter: top N terms per driver, then min-driver-recurrence -----

links <- sig_all %>%
  group_by(driver) %>%
  slice_min(order_by = p.adjust, n = TOP_N_PER_DRIVER, with_ties = FALSE) %>%
  ungroup()

cat("\n", nrow(links), " driver-term links remain after capping at TOP_N_PER_DRIVER = ",
    TOP_N_PER_DRIVER, " (", length(unique(links$ID)), " unique Hallmark terms).\n", sep = "")

term_freq <- links %>% count(ID, term_label = Description, name = "n_drivers") %>% arrange(desc(n_drivers))

if (MIN_DRIVERS_PER_TERM > 1) {
  keep_terms <- term_freq$ID[term_freq$n_drivers >= MIN_DRIVERS_PER_TERM]
  dropped_terms <- setdiff(links$ID, keep_terms)
  links <- links %>% filter(ID %in% keep_terms)
  cat(length(dropped_terms), " term(s) dropped by MIN_DRIVERS_PER_TERM = ",
      MIN_DRIVERS_PER_TERM, ": ", paste(dropped_terms, collapse = ", "), "\n", sep = "")
  term_freq <- links %>% count(ID, term_label = Description, name = "n_drivers") %>% arrange(desc(n_drivers))
}

if (nrow(links) == 0) {
  stop("No driver-term links survive PADJ_CUTOFF / TOP_N_PER_DRIVER / MIN_DRIVERS_PER_TERM -- ",
       "loosen these before plotting.")
}

cat("\n=== Final term frequency across drivers (top", nrow(term_freq), "terms) ===\n")
print(term_freq)

cat("\n=== Top 3 Hallmark terms by driver recurrence (sanity check vs manuscript story) ===\n")
print(head(term_freq, 3))

## ---- 7. Build the bipartite CHORD diagram (sector width = total flow) -----

sector_module <- setNames(driver_module$module, driver_module$gene)

driver_sector_order <- driver_module %>%
  mutate(regulon_size = regulon_sizes[gene]) %>%
  arrange(match(module, names(modules)), desc(regulon_size)) %>%
  pull(gene)

term_sector_order <- term_freq$ID
term_label_lookup <- setNames(term_freq$term_label, term_freq$ID)

n_drivers_n <- length(driver_sector_order)
n_terms_n   <- length(term_sector_order)

links$mlog10padj <- -log10(links$p.adjust)

# Ribbon/sector width = GeneRatio*100 (% of the driver's regulon -- inter-
# sected with the universe -- that falls in that Hallmark term). Chosen over
# a raw shared-gene count (or an unweighted per-term/per-driver count) on
# purpose: both alternatives were tried and both mechanically favor the two
# biggest regulons (KCMF1: 2579 targets, SRSF2: 1840) just because bigger
# gene sets have more statistical power to rack up significant terms, not
# because their regulation is more concentrated. GeneRatio is a proportion of
# each driver's own regulon size, so it does not have that bias -- see
# rowSums(value_mat) below for the resulting per-driver arc sizes.
links$ribbon_value <- links$GeneRatio_num * 100

value_mat <- matrix(0, nrow = n_drivers_n, ncol = n_terms_n,
                     dimnames = list(driver_sector_order, term_sector_order))
for (i in seq_len(nrow(links))) {
  value_mat[links$driver[i], links$ID[i]] <- links$ribbon_value[i]
}

cat("\n=== Per-driver total ribbon/arc weight (sum of GeneRatio*100 across its kept terms) ===\n")
print(sort(rowSums(value_mat), decreasing = TRUE))

# Per-cell ribbon color: origin driver's module color, opacity by -log10(padj)
# (secondary encoding; width/sector-size already carries GeneRatio). Cells
# with value 0 are never drawn so their color is irrelevant.
max_mlog10padj <- max(links$mlog10padj)
col_mat <- matrix("#00000000", nrow = n_drivers_n, ncol = n_terms_n,
                   dimnames = dimnames(value_mat))
for (i in seq_len(nrow(links))) {
  strength <- links$mlog10padj[i] / max_mlog10padj
  col_mat[links$driver[i], links$ID[i]] <-
    add_transparency(module_colors[sector_module[links$driver[i]]], 0.80 - 0.45 * strength)
}

grid_col <- c(setNames(module_colors[sector_module[driver_sector_order]], driver_sector_order),
              setNames(rep(TERM_SECTOR_COLOR, n_terms_n), term_sector_order))

# `group` is what makes chordDiagram() split the circle into a "driver half"
# and a "term half" (big.gap between groups, small.gap within) -- the chord
# equivalent of the two-big-gaps trick used manually in 5_2/this script's
# first draft.
sector_group <- setNames(c(rep("driver", n_drivers_n), rep("term", n_terms_n)),
                          c(driver_sector_order, term_sector_order))

draw_circos <- function() {
  # Allow sector labels to spill past the device's default plotting region
  # instead of being clipped at the canvas edge (same fix applied in
  # 5_2_Circos_regulon_overlap.R). canvas.xlim/ylim widened beyond the
  # default c(-1,1) for the same reason -- long Hallmark-term labels (e.g.
  # "REACTIVE OXYGEN SPECIES PATHWAY") need the margin, especially now that
  # some term sectors are narrow (low total value) and rotate their label
  # close to horizontal near the 9-o'clock position.
  old_par <- par(xpd = NA, mar = c(1, 1, 1, 1))
  on.exit(par(old_par), add = TRUE)

  circos.clear()
  circos.par(start.degree = 90, canvas.xlim = c(-1.35, 1.35), canvas.ylim = c(-1.35, 1.35))

  chordDiagram(
    value_mat,
    grid.col          = grid_col,
    col               = col_mat,
    group             = sector_group,
    order             = c(driver_sector_order, term_sector_order),
    big.gap           = 15,
    small.gap         = 2,
    directional       = 0,
    annotationTrack   = "grid",
    preAllocateTracks = list(track.height = 0.12),
    link.sort         = TRUE,
    link.largest.ontop = TRUE
  )

  # Custom label track (placed in the track pre-allocated above, just outside
  # the colored grid band): driver gene symbol, or the Hallmark term label
  # with the "HALLMARK_" prefix stripped.
  circos.trackPlotRegion(track.index = 2, bg.border = NA, panel.fun = function(x, y) {
    sector <- get.cell.meta.data("sector.index")
    xcenter <- get.cell.meta.data("xcenter")
    if (sector %in% driver_sector_order) {
      lab <- sector; cex_lab <- 0.75
    } else {
      lab <- term_label_lookup[sector]; cex_lab <- 0.5
    }
    circos.text(xcenter, 0.5, lab, facing = "clockwise", niceFacing = TRUE,
                 cex = cex_lab, font = 2)
  })

  # Explicit (x, y) instead of "bottomleft"/"bottomright": those keywords
  # anchor to the padded canvas corner (canvas.ylim[1] = -1.35), well below
  # where the circle's own labels actually end (~ -0.8), leaving a dead gap.
  # Placing the legends just under the circle instead keeps the whole figure
  # visually compact (see crop_png_whitespace() below for the outer-margin
  # side of the same problem).
  legend(x = -1.3, y = -0.98,
         legend = c(names(module_colors), "Hallmark term"),
         fill   = c(module_colors, TERM_SECTOR_COLOR),
         bty = "n", cex = 0.65, ncol = 2,
         title = "Driver functional module / node type")
  legend(x = 0.55, y = -0.98, legend = c("weaker", "", "stronger"),
         title = expression(-log[10](padj)~"(ribbon opacity)"), bty = "n", cex = 0.6,
         lty = 1, lwd = c(0.5, 1.75, 3), col = "grey30")
}

# Auto-crop the rendered PNG down to its actual content bounding box (plus a
# small pad), removing the blank margins that circos.par(canvas.xlim/ylim)
# necessarily leaves around a plot that isn't circular-symmetric in content
# (e.g. the empty big.gap wedge at the top, or a legend block shorter than
# the canvas half-height it's anchored to). This is the programmatic version
# of the manual Photoshop crop: read the PNG back in, find rows/cols that
# aren't (near-)white, and rewrite the file cropped to that box.
crop_png_whitespace <- function(path, pad_px = 15, bg_threshold = 0.98) {
  img <- png::readPNG(path)
  rgb <- img[, , 1:3, drop = FALSE]
  is_bg <- (rgb[, , 1] > bg_threshold) & (rgb[, , 2] > bg_threshold) & (rgb[, , 3] > bg_threshold)
  is_content <- !is_bg
  rows <- which(apply(is_content, 1, any))
  cols <- which(apply(is_content, 2, any))
  if (length(rows) == 0 || length(cols) == 0) {
    warning("crop_png_whitespace(): no non-background content detected in ", path,
            " -- leaving the file unmodified.")
    return(invisible(NULL))
  }
  r0 <- max(1, min(rows) - pad_px);          r1 <- min(dim(img)[1], max(rows) + pad_px)
  c0 <- max(1, min(cols) - pad_px);          c1 <- min(dim(img)[2], max(cols) + pad_px)
  png::writePNG(img[r0:r1, c0:c1, , drop = FALSE], path)
  cat("Cropped ", path, ": ", dim(img)[2], "x", dim(img)[1], " -> ",
      c1 - c0 + 1, "x", r1 - r0 + 1, " px\n", sep = "")
}

pdf(paste0(OUT_PREFIX, ".pdf"), width = 7, height = 7)
draw_circos()
dev.off()

png(paste0(OUT_PREFIX, ".png"), width = 7, height = 7, units = "in", res = 300)
draw_circos()
dev.off()

crop_png_whitespace(paste0(OUT_PREFIX, ".png"))
# NB: the PDF is left uncropped -- it's a vector file, so trimming its page
# box is a trivial, lossless operation in Illustrator/Acrobat/Inkscape if
# needed, and doing it here would require an external tool (e.g. pdfcrop)
# this repo doesn't otherwise depend on.

cat("\nSaved: ", OUT_PREFIX, ".pdf and .png\n", sep = "")
cat("Review the console tables above before dropping this into the manuscript ",
    "-- especially any 'zero significant terms' or GeneRatio/padj consistency warnings.\n", sep = "")
